sudo: required
services:
  - docker


before-install:
  - docker build -t medbm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true medbm/docker-react npm run test

deploy:
  provider: heroku
  api_key:
    secure: "2dfa5c1b-35f7-4150-8f83-9acb2fb0988b"
  on:
    branch : master
   
